### ISSUE TITLE
i dont get how to use this

### ISSUE THREAD

**Issue by Elmapul** [CodeReaper/unsealed-secrets#1]
i run this:

> sh create_new_key_pair.sh 
> Generating RSA private key, 2048 bit long modulus
> ...................................................................................................................+++
> .................................+++
> e is 65537 (0x10001)
> writing RSA key
> writing RSA key
> Signature ok
> subject=/CN=www.example.com/O=Example LTD./C=US
> Getting Private key

and open encode.php and decode.php on the browser but nothing happen

decode:

> sealed.json

encode:

> payload.json sealed.json

**Comment by CodeReaper** [comment]
After creating a new key pair in the terminal, you use the encode/decode not in a browser, but in the terminal as well.
E.g.:

```
php -f php/encode.php _shared/payload.json sealed.json
php -f php/decode.php sealed.json
```

**Comment by Elmapul** [comment]
oh, that is the problem, i was trying to use it on apache not on shell...

can you make an version for servers?

**Comment by CodeReaper** [comment]
If you open e.g. the encode.php file, you will see the PHP code you would use on apache and in the shell. The files are not a library, but an example to help people get started.
